#!/bin/bash

SLEEP_TIME=30

notification_loop() {
  while true; do send_notification "$1"; sleep $2; done
}

send_notification() {
  notify-send "Hey: $1"
}

while getopts 'm:t:' flag; do
  case "${flag}" in
    m) export MESSAGE="${OPTARG}" ;;
    t) export SLEEP_TIME="${OPTARG}" ;;
    *) break ;;
  esac
done

notification_loop "$MESSAGE" $SLEEP_TIME

